# Generated by Django 5.1 on 2024-08-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automobile', models.CharField(choices=[('Moto', 'Moto'), ('Carro', 'Carro')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('plate', models.CharField(blank=True, max_length=255, null=True)),
                ('buy_day', models.DateField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='document.document')),
            ],
        ),
    ]
