# Generated by Django 5.1 on 2024-10-02 20:07

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automobile', models.CharField(choices=[('Moto', 'Moto'), ('Carro', 'Carro')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('plate', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('buy_day', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
