# Generated by Django 5.1 on 2024-08-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicle_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='buy_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
