# Generated by Django 5.1 on 2024-09-26 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehicle_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='buy_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
