# Generated by Django 5.1 on 2024-10-01 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_vehicle_buy_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='document',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
