# Generated by Django 5.1 on 2024-09-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenance_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
