# Generated by Django 5.1 on 2024-09-26 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_maintenance_maintenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
