# Generated by Django 5.1 on 2024-10-02 22:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_gasoline', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), 'O preço não pode ser inferior a 0')])),
                ('value_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), 'O valor não pode ser inferior a 0')])),
                ('liters_gasoline', models.DecimalField(decimal_places=2, editable=False, max_digits=20)),
                ('refuel_date', models.DateField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refuels', to='vehicle.vehicle')),
            ],
        ),
    ]
