# Generated by Django 5.1 on 2024-08-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_gasoline', models.DecimalField(decimal_places=2, max_digits=20)),
                ('value_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('liters_gasoline', models.DecimalField(decimal_places=2, max_digits=20)),
                ('refuel_date', models.DateField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refuels', to='vehicle.vehicle')),
            ],
        ),
    ]
