# Generated by Django 5.1 on 2024-09-20 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refuel', '0002_alter_refuel_liters_gasoline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuel',
            name='price_gasoline',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0, 'Avaliação não pode ser inferior a 0')]),
        ),
        migrations.AlterField(
            model_name='refuel',
            name='value_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0, 'Avaliação não pode ser inferior a 0')]),
        ),
    ]
