# Generated by Django 5.1 on 2024-09-26 19:17

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refuel', '0003_alter_refuel_price_gasoline_alter_refuel_value_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuel',
            name='price_gasoline',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), 'O preço não pode ser inferior a 0')]),
        ),
        migrations.AlterField(
            model_name='refuel',
            name='refuel_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='refuel',
            name='value_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), 'O valor não pode ser inferior a 0')]),
        ),
    ]
