# Generated by Django 5.1 on 2024-09-26 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacement', '0003_replacement_description_replacement_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacement',
            name='replacement_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
